version: '3'

services:
  app:
    build: .
    container_name: locale-mapper-api
    volumes:
      - .:/home/node/app
  
  db:
    image: postgres
    container_name: lm-database
    restart: always
    tty: true
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata 
    ports:
      - '5432:5432'
    volumes: 
      - .data:/var/lib/postgresql/data/
