version: '3'

services:
  app:
    build: .
    container_name: locale-mapper-api
    volumes:
      - .:/home/node/app
  
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - .data:/var/lib/postgresql/data
      
volumes:
  db:
    driver: local
