version: '3'

services:
  app:
    build: .
    container_name: lm-api
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
  
  db:
    image: postgres
    container_name: lm-db
    restart: always
    tty: true
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=locale-mapper
    volumes: 
      - pgdata:/data/postgres

volumes:
  pgdata:
